### ISSUE TITLE
[lesion_detector_3DCE] visualize detected boxes

### ISSUE THREAD

**Issue by truetqy** [rsummers11/CADLab#12]
Hi,
How to visualize the detected results. I changed the parameter default.val_vis = True in rcnn/config.py but I got the error below:
----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "rcnn/tools/test.py", line 117, in <module>
    test_net(default.e2e_prefix, default.begin_epoch)
  File "rcnn/tools/test.py", line 90, in test_net
    default.val_max_box, default.val_thresh)
  File "rcnn/tools/test.py", line 75, in test_rcnn
    acc = pred_eval(predictor, test_data, imdb, vis=vis, max_box=max_box, thresh=thresh)
  File "/mnt/ssd500GB/project/CADLab/lesion_detector_3DCE/rcnn/tools/../../rcnn/core/tester.py", line 225, in pred_eval
    vis_all_detection(data_dict['data'].asnumpy(), boxes_this_image, imdb.classes, scale)
  File "/mnt/ssd500GB/project/CADLab/lesion_detector_3DCE/rcnn/tools/../../rcnn/core/tester.py", line 296, in vis_all_detection
    im = image.transform_inverse(im_array, config.PIXEL_MEANS)
  File "/mnt/ssd500GB/project/CADLab/lesion_detector_3DCE/rcnn/tools/../../rcnn/fio/image.py", line 158, in transform_inverse
    im += pixel_means[[2, 1, 0]]
IndexError: index 2 is out of bounds for axis 1 with size 1
----------------------------------------------------------------------------------------
The code works if I set default.val_vis = False. 

Could you please advice?

Thanks!

**Comment by studabyd** [comment]
Hello, Have you solved this problem, Now I want to visualize the detected picture, I want to have your answer. Thank you!
