### ISSUE TITLE
Error when I run 3DCE project with python=3.5 

### ISSUE THREAD

**Issue by studabyd** [rsummers11/CADLab#39]
@viggin , Hello,Sorry to bother you, I get an error:"ImportError: dynamic module does not define module export function (PyInit_bbox)" when my python version is 3.5. Just like the photo. I'm looking forward to your answer. Thank you!

**Comment by studabyd** [comment]
This is the code:
Traceback (most recent call last):
  File "/data/lcy/github/lesion_detector_3DCE/./rcnn/tools/train.py", line 16, in <module>
    from rcnn.core import callback, metric
  File "/data/lcy/github/lesion_detector_3DCE/rcnn/tools/../../rcnn/core/callback.py", line 6, in <module>
    from rcnn.tools.validate import validate
  File "/data/lcy/github/lesion_detector_3DCE/rcnn/tools/../../rcnn/tools/validate.py", line 4, in <module>
    from rcnn.tools.test import test_rcnn
  File "/data/lcy/github/lesion_detector_3DCE/rcnn/tools/../../rcnn/tools/test.py", line 11, in <module>
    from rcnn.core.loader import TestLoader
  File "/data/lcy/github/lesion_detector_3DCE/rcnn/tools/../../rcnn/core/loader.py", line 12, in <module>
    from rcnn.fio.rpn import get_rpn_testbatch, get_rpn_batch, assign_anchor
  File "/data/lcy/github/lesion_detector_3DCE/rcnn/tools/../../rcnn/fio/rpn.py", line 26, in <module>
    from rcnn.processing import bbox_transform
  File "/data/lcy/github/lesion_detector_3DCE/rcnn/tools/../../rcnn/processing/bbox_transform.py", line 7, in <module>
    from rcnn.cython import bbox
ImportError: dynamic module does not define module export function (PyInit_bbox)

**Comment by studabyd** [comment]
OK, Thamk you for your answer and time, It's useful!
